### ISSUE TITLE
Interface C++

### ISSUE THREAD

**Issue by bruno-cadorette** [bruno-cadorette/RealTimeGarbageCollector#1]
Comment est-ce qu'on pourrait interfacer avec un programme C++?
Une solution serait d'utiliser une classe RAII. Le désavantage de cette approche est que ce n'est pas transparent, et qu'il faut modifier un programme pour tester.

Une autre solution possible serait d'explorer certaines [des nouvelles fonctions de gestions de mémoire](http://en.cppreference.com/w/cpp/memory), tel que `declare_reachable` pour voir si c'est utile. On peut aussi [remplacer l'opérateur new](http://en.cppreference.com/w/cpp/memory/new/operator_new). Si l'interface est transparente, alors les tests vont être beaucoup plus facile à faire. 

Un truc bien serait de savoir a la compilation si un objet contient des pointeurs, ça pourrait nous facilité la tâche.

**Comment by JesseEmond** [comment]
J'ai regardé `declare_reachable` et autres, mais ça semble être uniquement utile pour les implémenteurs de compilateur (j'en comprend qu'ils peuvent rajouter du GC pour certains trucs) pour indiquer "ne GC pas ce ptr là". Par contre, ça n'a vraiment pas l'air supporté (pas de mon bord en tout cas) + ça ne nous serait pas vraiment utile ici (ça ne nous donne pas l'info qu'on veut).

Il y a moyen de se salir les mains et d'[embed de l'info sur les types](http://stackoverflow.com/a/11748131/395386) en y allant all-in sur les macros pour faire de la réflectivité, mais c'est encore un peu intrusif et ça a un certain coût additionnel.

Je vais aller dans la direction de remplacer le `new` pour l'instant, on va voir ce que ça donne.

**Comment by JesseEmond** [comment]
Après considération, je ne sais pas si `new` est une si bonne approche que ça, pour deux raisons:
- Ça nous enlève les places faciles où on peut *crowbar* notre passe de collection (ctor/dtor de `GCPtr`). Je ne pense pas que ce soit dramatique, parce qu'on pourrait quand même juste faire un `collect` parfois dans les `new` overloadés et on serait OK... Le plus gros problème, par contre:
- La situation suivante:
```cpp
struct Foo {
   int* memberPtr;
   void bar() {
      // ici on imagine que notre object Foo est un de nos GC roots ou quelque part dans l'arbre...
      int* p = new int{5}; // notre new est appelé, notre GC prend le ownership

      // !!!! PASSE DE GC::collect()
      GC::collect(); // pourrait être triggered par un dtor de GCPtr, un autre new, peu importe.
      // p est collecté.
      // ...

      memberPtr = p; // BOOM! On pointe sur de la mémoire désallouée
   }
};
```

Je pense que le problème fondamental ici est que `p` est un `root`, mais que l'overload de `new` ne gère pas les roots. Je ne vois pas comment on peut gérer nos roots sans être intrusifs (en utilisant le `new` overloadé)... Dans un monde idéal, ça aurait été cool d'utiliser `GCPtr` pour les roots et un `new` overloaded pour tout le reste, mais je ne pense pas qu'on gagne tant que ça en "non-intrusivité" à faire ça...

En gros, je pense que c'est difficile d'être non-instrusif sans être transparent sur les pointeurs membres **et** les roots (et je pense que détecter automatiquement le scope des roots de manière transparente c'est en dehors de notre scope).

Que dis-tu de juste utiliser des `GCPtr` partout où on prendrait des pointeurs? Ça va être déplaisant pour les exemples, mais ça évite les surprises du genre si on oublie de remplacer un root ptr...

**Comment by JesseEmond** [comment]
Handled by #13 .
