### ISSUE TITLE
Identifications des objets directement accessible par le programme (roots)

### ISSUE THREAD

**Issue by bruno-cadorette** [bruno-cadorette/RealTimeGarbageCollector#3]
Il faudrait un moyen de d'identifier les objets directement accessible par le programme, afin de pouvoir implémenter un algorithme de gc

IMPORTANT: il ne faut pas mélanger les données du garbage collecteur avec ceux du programme.
Plus d'information sur ce qu'est un root [ici](http://stackoverflow.com/questions/6366211/what-are-the-roots)

**Comment by JesseEmond** [comment]
Handled by #13 .
